### ISSUE TITLE
Add pkg-config support to help find headers

### ISSUE THREAD

**Issue by ghollisjr** [takagi/cl-cuda#102]
I added the following line to the top of driver-api/type-grovel.lisp:

(pkg-config-cflags "cuda" :optional t)

and this fixed a groveler build error on my system due to not being able to find CUDA headers without pkg-config.  Since it's optional, seems like it would be safe to add for everyone else as well.

**Comment by takagi** [comment]
Thanks! Would you post a pull request with the line added, so I can merge it to the master soon?

**Comment by ghollisjr** [comment]
Tested it and it works for me, thank you!
