### ISSUE TITLE
Cannot find CUDA SDK

### ISSUE THREAD

**Issue by Tibet256** [takagi/cl-cuda#42]
Hello,
Running latest CCL with Version 1.11-r16635 on OS X 10.10.5
Could load and compile cl-cuda without problem. 
I have a hard time referencing my version of CUDA which is NVIDIA-CUDA-7.5
When I run any cuda example, I get an error message:
e.g. (cl-cuda-examples.diffuse0:main)
> Error: CUDA SDK not found.
> While executing: CL-CUDA.DRIVER-API:CU-INIT, in process Listener(4).
How do I configure cl-cuda to reference the right framework ?
Should I recompile ?

Maybe a silly question - My first time using this library.

**Comment by takagi** [comment]
SDK-NOT-FOUND-ERROR is raised when cl-cuda can not refer CUDA SDK. The reference is defined in `src/driver-api/library.lisp`.

    (cffi:define-foreign-library libcuda
      (:darwin (:framework "CUDA"))
      (:unix (:or "libcuda.so" "libcuda64.so")))

This uses `DYLD_LIBRARY_PATH` environment variable on OSX for its reference path so that I export it in my `.bash_profile` as following:

    export DYLD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-6.5/lib

Please try this on your environment.

Sorry for the inconvenience. I should mention about it on README.

**Comment by Tibet256** [comment]
Thanks for the quick response. 
Could not make it work yet.
In my profile I have this: 
export DYLD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-7.5/lib:$DYLD_LIBRARY_PATH
export DYLD_FRAMEWORK_PATH=/Library/Frameworks/:$DYLD_FRAMEWORK_PATH
I believe load-foreign-library will use DYLD_FRAMEWORK_PATH 

I tried to get deeper and I tried:
(cffi:use-foreign-library libcuda)
> Error: Unable to load foreign library (LIBCUDA).
>          Error opening shared library /Library/Frameworks/CUDA.framework/Versions/A/CUDA : dlopen(/Library/Frameworks/CUDA.framework/Versions/A/CUDA, 10): no suitable image found.  Did find:
>        	/Library/Frameworks/CUDA.framework/Versions/A/CUDA: mach-o, but wrong architecture
>        	/Library/Frameworks/CUDA.framework/Versions/A/CUDA: mach-o, but wrong architecture

=> which is crazy because I am able to run CUDA separately from the command line (like the nbody example).
Something must be wrong with my setup.

**Comment by takagi** [comment]
Hmm... I have no idea about that now.

**Comment by Tibet256** [comment]
takagi
1) I wanted to thank you for committing some comments about the environment variables already :+1: 
2) I found my issue with the framework loading:
- my Clozure CL IDE was not bound to the 64bit version of ccl - So all the cffi calls were expecting 32bits library... I immediately changed it and now cl-cuda initializes SDK perfectly
- I suggest you may want to find a way to notify the user about the error when sdk is not found - Maybe a trivial format of the error in library.lisp ?
 3) As I went through the examples, I noticed another potential issue with the calls to nvcc in mvcc.lisp
- with my mac and the version 7.5 of CUDA, the arch option arch=sm_11 is not valid anymore and it crashes cl-cuda.  You need to update to arch=sm_20 to make it work.

Best

**Comment by takagi** [comment]
Thanks for sharing me your situation and suggestion.

> I suggest you may want to find a way to notify the user about the error when sdk is not found - Maybe a trivial format of the error in library.lisp ?

Yes. As you say I found current SDK-NOT-FOUND-ERROR is misleading so that I will think about it again.

> with my mac and the version 7.5 of CUDA, the arch option arch=sm_11 is not valid anymore and it crashes cl-cuda. You need to update to arch=sm_20 to make it work.

Thanks for this information. I can not catch up the latest CUDA. I will update the default arch number.
