### ISSUE TITLE
kernel `-` function does not correspond to lisp `-`

### ISSUE THREAD

**Issue by triskaj** [takagi/cl-cuda#89]
`(- 2 3 4)` is compiled to `2 - 3 - 4`, which does not correspond to lisp behaviour. It should be compiled to `2 - (3 + 4)`.

**Comment by takagi** [comment]
What resource specifies the behavior?

At least, I can't read the difference between `2 - 3 - 4` and `2 - (3 + 4)` from the description of CLHS [minus function](http://clhs.lisp.se/Body/f__.htm) :

```
If more than one argument is given, it subtracts all of the subtrahends from the minuend and returns the result.
```

**Comment by triskaj** [comment]
I'm sorry for wrongly describing the problem. If you compile `(- 2 3 4)` you get `(2 - (3 - 4))` in CUDA C which is different from `2 - (3 + 4)`.

**Comment by takagi** [comment]
Oh... it's completely wrong. Thanks for the report!

**Comment by triskaj** [comment]
No problem, I'm happy to help. It took me few hours to figure this out :-D.
